### ISSUE TITLE
Commands not working

### ISSUE THREAD

**Issue by abuhman** [OSSHealth/ghdata#3]
I've tried to run some of the commands in cli.py either from the command line or by adding a call from the page code.  It seems like they don't run and produce error messages.

I've tried:

Command line (with no changes to repo code):
python cli.py repo releases
python cli.py repo releases test_username
and other various combinations, but I get error messages, usually relating to having the wrong number of arguments (regardless of how many arguments I do or don't add.)

I've also tried just putting calls like
releases()
in the code of cli.py and seeing if it will run:
python cli.py
This also results in error messages.

Am I running these commands wrong?  Do they work right now (I mean, do they run without error messages.  I know they are skeleton commands)?

**Comment by howderek** [comment]
@abuhman Regarding the commands, for right now only 'users' works. Also, a configuration file is required. There is a bug that prevents running it without the config file (which makes it tough to generate a config file!).

`releases()` is not meant to be called directly. They are mangled by the [Click](http://click.pocoo.org/) decorators so [you have to call them from the Click context](http://click.pocoo.org/6/advanced/)

**Comment by abuhman** [comment]
Thanks for the instructions!  As far as the Click decorators, what benefits do those provide?  What do they help us do?

And as far as the commands not working, what should they do once they work?   What will we use them in order to do?

**Comment by howderek** [comment]
The Click decorators handle the command line argument parsing and they support more complex tools than docopt.

The commands will generate self-contained datasets.

**Comment by abuhman** [comment]
Okay thanks I think I understand better now.  I am working on trying to get some of the commands running.  I've gotten to the point where it is asking for the missing configuration file.  I have tried running the create_default_config command, which also asks for the missing configuration file.  Is there another way to obtain the configuration file?

**Comment by abuhman** [comment]
Actually, I have a further question: if we are calling this from the web, will we be able to use the command line?  Some searching I have done online suggests that trying to run things on the command line from the web is highly insecure as it provides the potential to influence the host machine/server.  

I'm not sure we will be able to use these commands with a web interface.

**Comment by howderek** [comment]
@abuhman I pushed an update that allows you to make the config without the db

There will be a CLI interface and a web interface. Both will use ghdata.py. The web interface will not touch cli.py or a shell. It is not worth building a web interface until we understand what's important.

**Comment by abuhman** [comment]
great, thanks!  How should I make the config?

**Comment by howderek** [comment]
@abuhman `ghdata create-default-config` after you installed the newest version.

**Comment by abuhman** [comment]
okay, thanks!  I have a default.cfg file now.

**Comment by GeorgLink** [comment]
Sounds like the issue was resolved.
@abuhman you reported the issue, can it be closed?

**Comment by howderek** [comment]
@GeorgLink the commands @abuhman mentioned are still not implemented. We can close the issue and move it to a milestone.

**Comment by howderek** [comment]
This issue is no longer relevant since we moved away from the CLI
